version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "v0.2"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "v0.2"
    schedule:
      interval: "daily"
