name: AutoRelease

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "v$semver"
          tag: "v$semver"
          changelog-entry: "$semver"
          regex: "/^Merge pull request #\\d+ from miguelnietoa\\/#{version}$/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
